version: '3'
services:
  mongoclient:
    image: mongo:4.4.3
    container_name: mongoclient
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts
    entrypoint:
      - /scripts/initiate-replica-set.sh
  mongodb:
    container_name: mongodb
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 5s
      timeout: 5s
      retries: 50
    image: mongo:4.4.3
    volumes:
      - mongodb-data:/data/db
    command: '--replSet rs0 --bind_ip_all'
    environment:
      MONGO_REPLICA_SET_NAME: rs0
    ports:
      - 27017:27017
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.8-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  rabbitmq-data:
  mongodb-data:
